/*  i2cdrvtest.c - The simplest kernel module.

#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/i2c.h>
#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR ("SD");
MODULE_DESCRIPTION ("eeprom_driver - loadable module template generated by petalinux-create -t modules");

//#define DRIVER_NAME "eepromtest"

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */

struct device_data *private_data;

static const struct i2c_device_id i2ctest_id[] = {
	{"I2C_TEST", 0 },
	{ }
};
MODULE_DEVICE_TABLE(i2c, i2ctest_id);

#ifdef CONFIG_OF
static const struct of_device_id i2ctest_dt_ids[] = {
	{ .compatible = "at,24c08", },
	{ }	
};
MODULE_DEVICE_TABLE(of, i2ctest_dt_ids);
#endif

static int i2ctest_probe(struct i2c_client *client,const struct i2c_device_id *id)
{
/* initialize device */
/* register to a kernel framework */
printk(KERN_INFO "probing i2ctest driver");
i2c_set_clientdata(client, private_data);
return 0;
}

static int i2ctest_remove(struct i2c_client *client)
{
private_data = i2c_get_clientdata(client);
printk(KERN_INFO "removing i2ctest driver");

/* unregister device from kernel framework */
/* shut down the device */
return 0;
}

static struct i2c_driver i2ctest_driver = {
	.probe = i2ctest_probe,
	.remove = i2ctest_remove,
	.id_table = i2ctest_id,
	.driver = {
	.name = "i2ctest",
	.owner = THIS_MODULE,
	.of_match_table = of_match_ptr(i2ctest_dt_ids),
	},
};

//extern int i2c_master_send(const struct i2c_client *client, const char *buf, int count);
//extern int i2c_master_recv(const struct i2c_client *client, char *buf, int count);

module_i2c_driver(i2ctest_driver);
